name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze
        continue-on-error: true

      - name: Run tests
        run: flutter test
        continue-on-error: true

        # basically, I just want to see the results of everything, some things will fail because they need the dotENV file.
